spring:
  # lazy init
  main:
    lazy-initialization: false
  # setup profiles
  profiles:
    active: demo
  # setup banner
  banner:
    location: classpath:banner.txt
    image:
      location: classpath:baniere.png
      height: 10
      width: 20
  # database setup - possible de faire appel au prop du pom.xml : ${prop}
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:memDB
    username: root
    password: pass
  jpa:
    database-plateform: org.hibernate.dialect.H2Dialect
    show-sql: true

# custom properties
custom:
  prenom: alexandre
  nom: kimtsaris